//用于定义按下另一个按键而松开另一个按键的内容
alias socd_switch_cancel_forward
alias socd_switch_cancel_back
alias socd_switch_cancel_right 
alias socd_switch_cancel_left 

//用于定义发送的内容
alias socd_switch_forward 
alias socd_switch_back 
alias socd_switch_right
alias socd_switch_left