exec MoClient/src/main/Features/Modules/Momot/_init_.mo
exec MoClient/src/main/Features/Modules/Crosshair/_init_.mo
exec MoClient/src/main/Features/Modules/RapidFire/_init_.mo
exec MoClient/src/main/Features/Modules/HudColorful/_init_.mo
exec MoClient/src/main/Features/Modules/Desubtick/_init_.mo
exec MoClient/src/main/Features/Modules/AntiFlash/_init_.mo
exec MoClient/src/main/Features/Modules/ThrowItems/_init_.mo
exec MoClient/src/main/Features/Modules/SmartActive/_init_.mo
exec MoClient/src/legacy/4items/_init_.cfg